//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabaratorinisDBEntities1 : DbContext
    {
        public LabaratorinisDBEntities1()
            : base("name=LabaratorinisDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lecture> lectures { get; set; }
        public virtual DbSet<module> modules { get; set; }
        public virtual DbSet<studentModule> studentModules { get; set; }
        public virtual DbSet<student> students { get; set; }
    }
}
